when:
  - event: [push, manual]

clone:
  git:
    image: ${DOCKER_PREFIX}/network-utils
    pull: true
    commands:
      - git clone ${CI_REPO_CLONE_URL} project
      - cd project
      - git checkout ${CI_COMMIT_SHA}
      - git submodule update --init --recursive
      - export REPO_REVISION=`git rev-list HEAD --count`
      - echo "ARTIFACT_PREFIX=${CI_REPO_NAME}_r$${REPO_REVISION}-${CI_COMMIT_SHA:0:8}_b${CI_PIPELINE_NUMBER}" >> envvars

steps:
  build_audioboard-v1:
    image: ${DOCKER_PREFIX}/gcc-arm-embedded
    pull: true
    commands:
      - cd project
      - cmake . -B build-audioboard-v1 -DPLATFORM=LPC11XX -DBOARD=audioboard_v1 -DCMAKE_TOOLCHAIN_FILE=libs/xcore/toolchains/cortex-m0.cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LTO=OFF -DUSE_WDT=ON
      - make -C build-audioboard-v1 -j `nproc`

  build_audioboard-v1-fixed:
    image: ${DOCKER_PREFIX}/gcc-arm-embedded
    pull: true
    commands:
      - cd project
      - cmake . -B build-audioboard-v1-fixed -DPLATFORM=LPC11XX -DBOARD=audioboard_v1 -DCMAKE_TOOLCHAIN_FILE=libs/xcore/toolchains/cortex-m0.cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LTO=OFF -DUSE_WDT=ON -DOVERRIDE_SW=32
      - make -C build-audioboard-v1-fixed -j `nproc`

  deploy:
    image: ${DOCKER_PREFIX}/network-utils
    pull: true
    commands:
      - cd project
      - source ./envvars
      - mkdir deploy
      - |
        for BUILD_DIR in "-audioboard-v1" "-audioboard-v1-fixed" ; do
          cd "build$${BUILD_DIR}" && find . ! -path "*CMakeFiles*" -name "*.hex" | xargs tar -cvJ -f ../deploy/$${ARTIFACT_PREFIX}$${BUILD_DIR}.tar.xz && cd -
        done
      - cd deploy
      - smbclient "//$${DEPLOY_SERVER_ENV}" -U "$${DEPLOY_USER_NAME_ENV}%$${DEPLOY_USER_PASSWORD_ENV}" -c "mkdir ${CI_REPO_NAME}" || true
      - smbclient "//$${DEPLOY_SERVER_ENV}" -U "$${DEPLOY_USER_NAME_ENV}%$${DEPLOY_USER_PASSWORD_ENV}" -c "cd ${CI_REPO_NAME}; mkdir ${CI_COMMIT_BRANCH}" || true
      - smbclient "//$${DEPLOY_SERVER_ENV}" -U "$${DEPLOY_USER_NAME_ENV}%$${DEPLOY_USER_PASSWORD_ENV}" -c "cd ${CI_REPO_NAME}/${CI_COMMIT_BRANCH}; prompt; mput *"
    environment:
      DEPLOY_SERVER_ENV:
        from_secret: DEPLOY_SERVER
      DEPLOY_USER_NAME_ENV:
        from_secret: DEPLOY_USER_NAME
      DEPLOY_USER_PASSWORD_ENV:
        from_secret: DEPLOY_USER_PASSWORD
